### ISSUE TITLE
This aint an os you tripping bro

### ISSUE THREAD

**Issue by llucere** [Maknio/TextOS#1]

**Comment by llucere** [comment]
At least make your own version of batch and call it 'TextBat' not TextOs
like where tf the bootloader

**Comment by lammersbjorn** [comment]
Aw man it's just a fun project, let man do what he wants to.

**Comment by llucere** [comment]
> Aw man it's just a fun project, let man do what he wants to.

Ill do his mom

**Comment by lammersbjorn** [comment]
D:
